### ISSUE TITLE
Feature request: attribute whitelist

### ISSUE THREAD

**Issue by mcodev1** [tjwebb/sails-permissions#187]
CriteriaPolicy currently supports an attribute blacklist.

Creating a whitelist can be accomplished by just blacklisting the attributes that I don't want as part of the whitelist, but it would need to be updated if the schema changes and an additional attribute is added. A whitelist would allow me to define a set of attributes and disallow all others, including new ones in the future.

Creating a permission with both a blacklist and a whitelist would presumably not be allowed.

```js
Permission.create({
    "model": "car",
    "action": "update",
    "role": "registered",
    "relation": "owner",
    "criteria": {
        "whitelist": ["paintColor", "fuelLevel"]
    }
});
```

**Comment by tjwebb** [comment]
Unfortunately we can't accommodate this feature; below are the reasons why.

#### Philosophical Issues
Criteria are always subtractive, never additive. Because Permissions *grant* privileges rather than restrict them, Criteria are used to invalidate a granted Permission if certain specific conditions hold. That is, Criteria are designed to hide what would otherwise be visible. Therefore if you add an attribute to a model, it is by design that you'd need to explicitly add that new attribute to the Criteria blacklist, since Permissions by default should grant privileges unless a Criteria specifically and intentionally curtails them.

#### Practical Issues
> Creating a permission with both a blacklist and a whitelist would presumably not be allowed.

This is one practical issue created by allowing both whitelists and blacklists. Every time a Permission or Criteria were created or updated, we'd have to query to ensure that each Permission contains no two Criteria for the same `model` that contain both a whitelist and blacklist.

The second practical issue is that a Permission could not contain two Criteria for the same `model`, `action`, and `criteria` that contain non-identical whitelists, because it would constitute a logical inconsistency. If one Criteria says I can only see attribute `x`, and the other says I can only see attribute `y`, one of them *must* be wrong. This is basically a divide-by-zero. For duplicate blacklists, we can simply concatenate both lists and black out all the attributes in the resulting list with no problem.

**Comment by ryanwilliamquinn** [comment]
Currently, only one permission is ever considered for a model, so I don't see the non-identical whitelists being an issue.  Sure, it doesn't make sense, but it is essentially operator error.  As it is, we aren't concatenating blacklists as far as I know.

**Comment by tjwebb** [comment]
> Currently, only one permission is ever considered for a model, so I don't see the non-identical whitelists being an issue.

Yea, I'm saying it's an issue if that one Permission has multiple conflicting Criteria.

>  As it is, we aren't concatenating blacklists as far as I know.

Right, behavior around this is essentially "undefined" currently. But we can choose how to handle this without ending up in a corner we can't escape from.

**Comment by mcodev1** [comment]
> For a blacklist, choosing one Criteria might result in an incomplete "blacking out" of the attributes to be hidden. In the case of a whitelist, choosing one of the Criteria might utterly contradict another.

I'm not understanding the difference here. How is it that an incomplete blacklist as a result of duplicate criteria is not a contradiction? Just in the same way that a whitelist is an inverted blacklist, so too is a blacklist an inverted whitelist. If there are two criteria for the same model and action with different criteria, and one of them gets chosen arbitrarily, then that one blacklist is necessarily revealing more information than the other would.

**Comment by tjwebb** [comment]
> How is it that an incomplete blacklist as a result of duplicate criteria is not a contradiction?
> and one of them gets chosen arbitrarily,

Because blacklists can be concatenated to form a correct (i.e. more complete) blacklist. Whitelists can never do this. This is not being done currently. I apologize if my case above was overly hypothetical.

There is of course a technical solution, here, which is to disallow multiple Criteria with identical model/action combinations in the first place for a given Permission. In that case, a whitelist could be shown to be reliable, but this still is still antithetical to the purpose of Criteria. 

My overall point is that we already have a way to black out attributes. I don't want to add another way, which does the same thing, but adds convenience for a particular use case. I see your point that this would make some things easier for you, but I need to balance that against a desire to keep the framework clean and reliable for everyone else.
